day1co/pebbles

src/json-web-token/index.ts
json-web-token - index에 인터페이스이름이 잘못 작성됨.
인터페이스 이름 수정함.
로컬 테스트
=> util: interface `I` prefix 삭제

src/date-util/date-util.ts
import 순서를 convention에 맞게 수정
export할 필요가 없는 namespace 내의 함수는 namespace 밖으로
코드를 import -> constant -> function 순서로 변경
=> 컨벤션에 맞추기 위한 수정

src/number-util/index.ts, src/number-util/number-util.spec.ts, src/number-util/number-util.ts
- input값을 integer로 변환하는 intValueOf와 number로 변환하는 valueOf 추가
테스트코드
=> feat: number-util 추가

src/string-util/string-util.spec.ts, src/string-util/string-util.ts
boolean을 반환하는 함수들이므로 is~가 더 나은 이름이다
함수명 변경
=> validate 함수 이름 변경

src/object-util/object-util.spec.ts, src/object-util/object-util.ts
https://fastcampus.atlassian.net/browse/PF-37
로컬테스트
=> redstone obj.js에 있는 isNullish를 TypeScrpit 로 rewriting

src/date-util/date-util.ts, src/http-client/http-client.ts, src/logger/logger.spec.ts, src/object-util/object-util.ts
logger name에 pebbles가 들어가도록 수정
=> logger name 수정

src/misc-util/index.ts, src/misc-util/misc-util.interface.ts, src/misc-util/misc-util.spec.ts, src/misc-util/misc-util.ts, src/misc/index.ts
Misc를 MiscUtil로 이름 변경
getPagination() 구현 (backoffice의 getPagination() 참고. redstone/util/pagination과는 다름)
npm run test
=> getPagination() 구현

src/string-util/string-util.spec.ts, src/string-util/string-util.ts
=> feat: string-util에 midmask 함수 추가

.github/workflows/pr-labeler.yml, .github/workflows/release-drafter.yml
workflows/release-drafter.yml 추가
=> workflows/release-drafter.yml 추가 및 pr-labeler.yml 변경

src/date-util/date-util.spec.ts
`parseByFormat`의 중복되는 테스트코드를 삭제했습니다.
테스트코드
=> fix: delete duplicated test code at date-util

.github/workflows/npm-publish.yml
* PR이 병합 시 publish가 되지 않고있습니다.
* 모든 path 설정에서 특정 path는 제외되도록 수정합니다.
* https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#excluding-paths
=> workflow: npm publish할 때 타겟 paths-ignores 설정

package.json
package.json의 types 항목에 index.d.ts를 index.d.js라고 해놨다.
=> index.d.ts 오타 수정

package.json
pr#66 merge 이후 build 실패
package.json의 버전을 0.0.2에서 0.0.3으로 올림
=> fix:package.json 버전 0.0.3으로 올림

.github/npm-publish-slack.sh, .github/workflows/npm-publish.yml
* publish 에서 슬랙 전송 오류
* 비워져있던 코드를 채워줍니다.
=> workflow: 슬랙 메세지전송 코드를 호출할 때 hook url을 전달

package-lock.json
#71 에서 package-lock.json이 누락
* 최신 package-lock 파일을 추가
=> fix: package-lock.json을 최신화

.github/workflows/release-drafter.yml
- 권한 문제로 release drafter가 정상 작동하지 않습니다.
권한을 추가하였습니다.
=> workflow: fix release drafter add wirte permission

.github/npm-publish-slack.sh, .github/workflows/npm-publish.yml
https://day1c.slack.com/archives/C026QABGNFP/p1641192777095500?thread_ts=1641190870.094100&cid=C026QABGNFP
-> 패키지 업데이트 내용을 수기로 작성중
change log가 슬랙 메세지에 포함되도록 하려 합니다.
pebbles로 테스트한 뒤에 redstone에도 적용시킬까 합니다.
=> workflow: npm-publish-slack-message에 change log가 포함되도록 합니다

.github/workflows/npm-publish.yml
https://github.com/day1co/pebbles/runs/4724551884?check_suite_focus=true#step:6:174
변수 사용법이 올바르지 않아 스크립트 실행이 실패합니다.
CHANGE_LOG 변수 사용 부분을 수정합니다. `$(CHANGE_LOG) => "$CHANGE_LOG"`
=> fix: npm-publish.yml 파일의 script 문법 오류를 수정합니다

.github/npm-publish-slack.sh
sh 실행 실패 : https://github.com/day1co/pebbles/runs/4735668242?check_suite_focus=true#step:6:175
CHANGE_LOG 변수를 문자열로 감싸줍니다.
https://day1c.slack.com/archives/C026QABGNFP/p1641192777095500?thread_ts=1641190870.094100&cid=C026QABGNFP
로컬테스트
https://day1c.slack.com/archives/C026QABGNFP/p1641536804000900
=> fix:npm publish의 CHANGE_LOG 변수를 문자열화 합니다

src/object-util/object-util.ts
number | string | symbol 대신 ObjectKeyType을 적용
npm run test
=> refactor: ObjectKeyType 적용

src/object-util/object-util.spec.ts, src/object-util/object-util.ts
redstone/util/obj 의 `isEqual`을 구현합니다.
object-util에 `isEqual`을 추가합니다.
테스트 코드
=> feat:object util is equal

package-lock.json, package.json, src/number-util/number-util.spec.ts, tsconfig.json
package vulerability 문제 해결
eslint 버전 변경 후 유효한 precision 범위를 벗어난 floating number에서 lint 에러 발생
typescript와 eslint 버전 up
npm install --legacy-peer-deps
floating number에 대한 NumberUtil.valueOf 테스트는 NumberUtil.valueOf().toString() 으로 비교
"@typescript-eslint/eslint-plugin": "^5.10.1",
"@typescript-eslint/parser": "^5.10.1",
"eslint": "^8.7.0",
"eslint-plugin-prettier": "^4.0.0"
"typescript": "^4.5.5"
npm run test
=> floating number에 대한 lint 오류 수정 및 package vulerability 해결

package.json, src/object-util/object-util.spec.ts, src/object-util/object-util.ts
lodash의 pick()과 동일한 함수가 필요
pick() 구현
테스트에서 불필요한 async 제거
npm run test
=> ObjectUtil.pick() 구현

src/date-util/date-util.spec.ts, src/date-util/date-util.ts
https://github.com/fastcampus/redstone/pull/581/files#r793125862
isValidDate라는 함수가 유용하게 쓰일 것 같아 export하도록 수정하려 합니다
isValidDate 함수를 DateUtil namespace에 포함합니다
isValidDate 함수의 테스트코드를 작성합니다
테스트코드
=> refactor: isValidDate를 export하도록 합니다

src/date-util/date-util.interface.ts, src/date-util/date-util.ts, src/string-util/string-util.ts
코드 상의 warning 제거
substr() 대신 substring()을 쓰도록 수정
npm run test
=> deprecated 함수(substr) 대체 및 코드 정리

.github/workflows/ci-test.yml, .github/workflows/npm-publish.yml
workflow 파일들을 redstone 프로젝트 것과 맞춰서 변경
=> workflow: redstone의 workflow 파일에 맞춰서 변경

src/http-client/http-client.spec.ts, src/misc-util/misc-util.spec.ts
http-client의 실제 http 통신 테스트 추가
테스트 실행 전 테스트 서버를 띄우고 테스트 실행 후 종료하도록 함
npm run test
=> http-client 테스트 추가

src/date-util/date-util.spec.ts, src/date-util/date-util.ts
해당 날짜가 이번달의 마지막 날인지 확인이 필요하다.
해당 날짜에 +1일을 하여 조회된 일자가 1일이면 마지막 날임을 확인하도록 구현하였습니다.
테스트 코드
=> feat: 해당 날짜가 마지막 날인지 체크하는 함수

src/number-util/number-util.spec.ts, src/number-util/number-util.ts
문자열이 숫자인지 확인하는 기능이 필요합니다. 
NumberUtil 에 isNumeric 을 추가하였습니다. 
https://stackoverflow.com/a/1830844
npm test
=> Add isNumeric method to NumberUtil

src/http-client/http-client.spec.ts, src/http-client/http-client.ts, src/misc-util/misc-util.interface.ts, src/misc-util/misc-util.ts, src/object-util/object-util.ts, src/string-util/string-util.interface.ts, src/string-util/string-util.ts, tsconfig.json
interface 멤버에 readonly를 붙이지 말고 Readonly<> 타입을 이용하자
StringUtil.getNonce()의 길이 제한을 없애자
http-client 테스트를 서버 없이도 동작하도록 하자
함수 입력인자 타입에 Readonly 적용
충분한 길이의 문자열이 나올때까지 getNonce 내에서 Math.random().toString(nonceEncoding) 반복
http-client 테스트 시에 axios를 mock하도록 수정
npm run test
=> Readonly 적용

package-lock.json, src/date-util/date-util-base.type.ts, src/date-util/date-util.interface.ts, src/date-util/date-util.spec.ts, src/date-util/date-util.ts, src/date-util/date-util.type.ts, src/date-util/index.ts, src/index.ts
서버 시간대는 언제나 utc인데 로컬 타임을 출력해야하는 경우가 있다
요일에 대한 출력을 할 수 있어야한다.
Date 인스턴스의 로컬 타임이 아닌, 입력받은 timeZone에 맞춰 포맷하도록 수정
포맷에 ddd / dddd가 있으면 (locale에 맞춰) 요일을 출력하도록 변경
npm run test
=> format이 임의의 타임존에 대해 출력 가능하도록 수정

src/misc-util/misc-util.spec.ts
allow 10ms error 테스트 케이스가 오류가 나는 경우가 종종 있습니다. 
https://developer.mozilla.org/ko/docs/Web/API/setTimeout#%EB%94%9C%EB%A0%88%EC%9D%B4%EA%B0%80_%EC%A7%80%EC%A0%95%ED%95%9C_%EA%B0%92%EB%B3%B4%EB%8B%A4_%EB%8D%94_%EA%B8%B4_%EC%9D%B4%EC%9C%A0
setTimeout 을 이용해서 delay 를 지정할 경우 지정한 시간 보다 오래걸릴 수 있습니다. 
그 것이 10ms 이하가 될 것인지 보증할 수 없습니다. 
따라서 해당 테스트 케이스는 삭제하는게 좋을 것 같습니다.
=> remove: allow 10ms error

package-lock.json, src/index.ts, src/string-util/index.ts, src/string-util/string-util.const.ts, src/string-util/string-util.ts
기존 fastcampus/util의 escapeCsv()가 필요하다
StringUtil에 escapeCsv() 추가, 다만 deprecated 상태로 넣음.
const UTF8_BOM_STR 추가
=> escapeCsv() 추가

README.md, src/index.ts
지난 작업으로 추가된 time-range 기능을
외부프로젝트에서 불러올수있도록 index.ts에 경로추가 합니다.
=> index에서 time-range 경로추가

src/object-util/object-util.spec.ts, src/object-util/object-util.ts
merge() 실행 중 Cannot redefine property: arguments 에러가 발생.
Function type에 대한 deepClone()이 문제로 보여짐.
clone 대상이 Function인 경우는 deepClone이 필요하지 않으므로 그 자신이 반환되도록 수정
merge 할 때 대상이 Function인 경우는 primitive type과 동일하게 취급
https://day1c.slack.com/archives/C01BY5C1QVB/p1652144920934779
npm run test
=> deepClone()과 merge()에서 Function type에 대한 처리 추가

package-lock.json, src/object-util/object-util.spec.ts, src/object-util/object-util.ts
객체에서 omit하려는 대상 key가 없으면 return으로 루프를 빠져나와버리는 오류가 있어서
omit이 제대로 동작하지 않는 버그가 있다.
omit 대상 key 목록에 객체에 불포함된 key가 있는 테스트 케이스를 추가
for 도중 대상 key가 없으면 return 하는 오류 수정
for 대신 forEach로 변경
npm run test
=> omit 처리 도중 키가 일치하지 않는 경우 이후의 처리가 제대로 되지 않는 버그

src/index.ts, src/map-util/index.ts, src/map-util/map-util.spec.ts, src/map-util/map-util.ts
Map Object를 다루는 MapUtil를 추가한다.
MapUtil namespace 추가
`MapUtil.get(map, key, defaultValue)` 추가 
스펙 추가
=> feat: Add MapUtil

package-lock.json, src/exception/index.ts, src/exception/server-exception/index.ts, src/exception/server-exception/unknown-exception.ts, src/index.ts
UnknownException 클래스가 필요하다
UnknownException 클래스 추가
=> UnknownException 클래스 추가

src/logger/logger-impl/pino-logger.ts, src/logger/logger.interface.ts, src/logger/logger.type.ts
pino 로거의 verbose 레벨(10) 로그를 남기는 trace 함수를 추가합니다.
=> feat: Logger 에 trace 레벨을 추가

package-lock.json, package.json, src/logger/logger-impl/pino-logger.ts, src/logger/logger.interface.ts
error.stack의 타입이 string | undefined이기 때문에 기존 logger에서는 번잡한 분기문이 필요하다.
```typescript
logger.debug(error.stack ? error.stack : '');
```
message template string이 undefined면 null string으로 대체
pino 버전 업
=> logger에서 undefined를 빈 스트링으로 처리하도록 수정

src/object-util/object-util.spec.ts, src/object-util/object-util.ts
배열 요소에 null 이 있으면 deepClone()이 실패한다.
typeof null === 'object'
typeof undefined === 'undefined'
npm run test
=> 배열 요소에 null이 있어도 복사 가능해야한다

src/object-util/object-util.ts
is_nullish 는 type guard 로 동작하지 않는다.
is_nullish 를 type guard 로 사용하고 싶어 predicate 를 추가합니다.
https://www.typescriptlang.org/docs/handbook/2/narrowing.html#using-type-predicates
=> feat: is_nullish 에 type predicate 추가

src/index.ts
TokenExpiredException을 루트에서 export 하도록 수정하였습니다.
```typescript
// AS-IS
import { TokenExpiredException } from '@day1co/pebbles/lib/exception'
// TO-BE
import { TokenExpiredException } from '@day1co/pebbles'
```
=> feat: export TokenExpiredException in root

src/map-util/map-util.spec.ts, src/map-util/map-util.ts
This reverts commit a4bbb6bd5350508db80fc5ff3c4f4e352cda7a09.
origin head 를 잘못지정해 main 에 바로 푸시 되었습니다. 
git revert
=> Revert "feat: Add MapUtil.groupByKey"

src/index.ts
=> fix: MapUtil is not a type 

src/array-util/array-util.spec.ts, src/array-util/array-util.ts, src/array-util/index.ts, src/index.ts
두 배열간 innerJoin 과 leftJoin 처럼 동작하는 메서드 추가
=> feat: ArrayUtil.innerJoin / leftJoin

src/map-util/map-util.spec.ts, src/map-util/map-util.ts
* nested object 환경에서 사용하기 편하도록 callback 을 인자로 받는 groupBy 를 추가합니다.
=> feat: MapUtil.groupBy 추가

src/number-util/number-util.spec.ts, src/number-util/number-util.ts
toPermyriad와 fromPermyriad 메소드를 추가합니다.
string도 받아주어야할지 결정이 필요합니다.
number-util에 toPermyriad와 fromPermyriad를 추가
테스트 코드
=> number-util: feat add toPermyriad and fromPermyriad

src/date-util/date-util.ts
포맷별 기본지원되는 함수가 다른데 쓸때마다 무슨 포맷에 뭘 써야하는지 몰라서 pebbles 소스코드를 뒤져봐야 한다.
간단한 디스크립션을 추가해서 사용할때 무슨 포맷에 대한 함수인지 판별할 수 있도록 한다.
휴먼아이
=> refactor: Add some descriptions about date-util functions

src/index.ts
=> fix: index.ts에 TypeUtil 정의 누락된 것들 추가

src/number-util/number-util.ts
NumberUtil.toPermyriad의 undfined 리턴타입을 제거합니다.
=> fix: toPermyriad의 return type에 undefined 제거

src/misc-util/misc-util.spec.ts, src/misc-util/misc-util.ts
페이지 번호와 개수를 받아 limit offset을 반환해준다.
=> feat: add setNextPagination

src/string-util/string-util.spec.ts, src/string-util/string-util.ts, src/string-util/string-util.type.ts
기존의 마스킹과는 별도로 앞 6자리를 제외한 뒷자리를 마스킹하거나 숫자들을 모두 마스킹 하는 함수를 새로 추가합니다.
=> add masking tax identification number

src/array-util/array-util.spec.ts
=> fix: array-util 스펙 수정

.github/workflows/ci-test.yml, .github/workflows/npm-publish.yml
day1co/actions 사용으로 변경 (actions/setup-node 따라가도록)
npm-publish의 actions/setup-node v4로 변경
=> workflow: setup-node@4

src/money-util/money.type.ts
빌드 경고 수정
https://github.com/day1co/pebbles/pull/202#discussion_r1432282227
=> money-util: fix typing for unused vars

package-lock.json, package.json, src/array-util/array-util.spec.ts, src/exception/exception.spec.ts, src/money-util/money.type.ts, src/time-range/time-range.ts
월간 정기 보안 점검을 수행합니다.
https://fastcampus.atlassian.net/browse/SEC-5056
npm audit 검수 및 변경 사항 확인
axios 의 메이저 버전 변경
=> misc: npm audit fix for axios

package-lock.json, package.json, src/crypto-util/crypto-util.spec.ts, src/crypto-util/crypto-util.ts, src/crypto-util/index.ts
암호화에서 자주 사용되는 함수들을 추가
Pebbles 는 Nodejs / Web 환경에서 모두 사용되기 때문에 Web Crypto 를 이용해 처리.
`globalThis.crypto` 를 사용하기 위해 package.json 의 engines 을 `"node": ">=20.0.0"` 로 처리 
* https://nodejs.org/api/webcrypto.html
* https://nodejs.org/api/crypto.html
* @types/node 에 crypto 가 globalThis 로 추가되어있지 않아 `@ts-ignore` 처리
=> feat: CryptoUtil 추가

src/index.ts
CryptoUtil 이 index 에 노출되지 않아 수정합니다.
=> fix: CryptoUtil to index

.github/dependabot.yml
Security에 Critical 이슈가 있음
https://github.com/day1co/pebbles/security/dependabot
dependabot 설정 추가
아래 참고해서 `allow: - dependency-type: 'all'` 로 지정했는데 혹시 옵션 수정이 필요할지 확인 부탁드립니다.
https://github.com/fastcampus/fastcampus-api/pull/167
https://docs.github.com/ko/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file
같은 이슈가 있는 레포지토리는 아래와 같다고 하네요.
https://github.com/advisories/GHSA-67hx-6x53-jw92/dependabot?query=user%3Aday1co+user%3Aday1coloso+user%3Afastcampus+user%3Aday1snowball
x
=> misc: add dependabot

src/crypto-util/crypto-util.ts
lib.dom.d.ts 가 import 되어있는 프로젝트에서는 오류가 발생
declare 내용을 지우고 (globalThis as any) as typeof webcrypto 로 변경
=> fix: remove declare globalThis crypto

src/http-client/index.ts
=> chore: export type HttpError

src/index.ts
http-client 최상단에서 export 누락
휴먼 아이..
=> chore: export type HttpError from root

package-lock.json, package.json, src/object-util/object-util.ts
1. 변수명 constructor 는 예약어임. 
2. 조건문에 타지 않았을 경우에 constructor ? new constructor() : ... 이부분이 constructor 가 함수가 아닌경우 문제가 됨.
예약어인 constructor 를 생성자 변수명으로 사용하지 않는다. 
생성자가 함수일 때만 함수로 실행 가능하도록 수정, 이외에는 new Object
smoke test
=> fix: ObjectUtil deepClone 버그 수정

src/exception/client-exception/conflict-exception.ts, src/exception/client-exception/index.ts, src/exception/exception.spec.ts
skillflo-api 에서 409 error 사용이 필요합니다.
https://fastcampus.atlassian.net/browse/FCLXP-5705?atlOrigin=eyJpIjoiNzg4OGI4NDlmMzY5NDI4NGJlZTNhOGNmNGRiYjY5NWQiLCJwIjoiaiJ9
conflict exception 을 생성했습니다.
Test code
=> feat : conflict-exception 생성

src/index.ts, src/search-util/index.ts, src/search-util/search-util.spec.ts, src/search-util/search-util.ts
정렬된 내용에서는 선형 탐색보다 이진탐색이 유용하다.
데이터가 많은 경우에만 한정적으로 사용할 예정
=> feat: binary search 추가

src/date-util/date-util.const.ts, src/date-util/date-util.spec.ts, src/date-util/date-util.ts
회원가입 시, 생일 데이터는 성인만 받도록 한다.
https://fastcampus.atlassian.net/browse/COL-5663
성인 체크 함수 추가
=> feat: add isAdult function

src/date-util/date-util.spec.ts, src/date-util/date-util.ts
=> feat: isAdult timezone 지원

src/date-util/date-util.spec.ts
카카오에서 오는 생년월일 case 참고용 테스트코드 추가
=> feat: isAdult test case 추가

src/exception/client-exception/index.ts, src/exception/index.ts, src/index.ts
exception 사용을 위해 export
index에 추가
x
휴먼 아이
=> fix: export exception

src/crypto-util/crypto-util.spec.ts, src/crypto-util/crypto-util.ts, src/crypto-util/ezwel-seed.d.ts, src/crypto-util/ezwel-seed.js
이지웰 서버와 통신에 사용되는 seed 암호화/복호화 코드를 추가합니다.
국내에서 얻을 수 있는(이 알고리즘은 국내 전용, 1999년 KISA) js 코드는 3가지가 있는데...
이게 이지웰에서 인코딩된 방식으로 동작합니다.
https://github.com/eunbok/crypto-js
테스트 케이스 추가
실제 사용된 키 정보는 저장소에 올리지 않기 위해 테스트 케이스도 제거합니다.
=> feat: add ezwel seed encoder/decoder method

tsconfig.json
=> feat: change compiler options for js file

src/crypto-util/TextEncoder.d.ts, src/crypto-util/crypto-util.spec.ts, src/crypto-util/crypto-util.ts
- 버그 수정
#238 #239 #240
#240에서 마저 안 지운 node:util 임포트를 삭제
=> fix: remove TextEncoder from node:util
