- src/string-util/string-util.spec.ts
- src/string-util/string-util.ts
기존 util에 있는 `join`과 `joinTags` 함수가 코드 유사점이 많아 타입으로(array element type이 string인지, Tag타입인지) narrowing하는 `join`이라는 함수 하나로 묶었는데 이 부분에 대해서 다른분들 의견이 궁금합니다!
참고로 split과 splitTags도 유사한 점이 많았지만.. 하나로 묶기에는 분기점을 설정할만한 포인트를 못 찾아서..
생각해봤던건 parameter값에 `isReturningTags: boolean`을 넣는것이었는데 이건 뭔가 이상한 거 같아서 일단 별개의 함수로 만들어놓았습니다.
로컬테스트
> feat: join과 joinTags와 join 함수를 결합 + split 함수 별도 생성(PF-8)

- src/date-util/date-util.spec.ts
- src/date-util/date-util.ts
https://fastcampus.atlassian.net/browse/PF-28
- Redstone(JS)에서 `parseTimestamp`가 여러곳에서 사용되는 것을 확인하여 구현함.
- token으로 `fmt`를 구분후 해당하는 위치의 `str`을 날짜에 사용되는 시간으로 사용
- PR에서의 논의 결과 string format을 받아 Date함수를 리턴하는 `parseByFormat`과 `parseByFormat`을 호출하는 특수한 상황인 `parseByTimestamp` 두가지 함수를 구현했습니다.
(https://github.com/day1co/pebbles/pull/25#discussion_r740669142 에서의 논의)
> `DateUtil#parseByFormat` / `parseByTimestamp` 구현

- src/boolean-util/boolean-util.spec.ts
- src/boolean-util/boolean-util.ts
- src/boolean-util/index.ts
- 기존 redstone/util의 str.js에 있던 toBoolean 구현
- string타입 인자를 정규표현식으로 true / false 여부 판단
로컬테스트
> feat: boolean-util의 valueOf 추가(PF-8)

- src/date-util/date-util.spec.ts
- src/date-util/date-util.ts
* https://fastcampus.atlassian.net/browse/PF-29
* second의 number를 받아 time 포맷 `00:00:00` 으로 리턴하는 함수 추가
> feat: date-util - second를 받아 time 포맷으로 리턴하는 함수 추가 (PF-29)

- src/string-util/string-util.spec.ts
- src/string-util/string-util.ts
- validatePhoneNumber -> 010 XXXX XXXX이거나 070 XXXX XXXX 형식인지 검증하는 함수
- normalizePhoneNumber -> 인자값의 전화번호를 통일된 형태로 return
- redstone/util/str.js의 normalizePhoneNumber와 normalizePhone 함수를 통합하려 함
로컬테스트
> feat: string-util에 validatePhoneNumber와 normalizePhoneNumber 추가

- src/string-util/string-util.spec.ts
- src/string-util/string-util.ts
- redstone/str의 validateEmail 이관
- 기존에 쓰던 정규표현식보다 좀 더 엄격한 룰의 정규표현식을 사용했습니다. (ex: 기존에는 test@test도 통과되었는듯 하나 통과가 안되도록)
테스트코드
> feat: validateEmail 함수 추가

- src/date-util/date-util.spec.ts
- src/date-util/date-util.ts
`toDate`를 `parse`로 이름 변경하여 `new Date()` 로 대응가능한 변수들을 처리하도록 했습니다.
참고: redstone에 있던, string format를 받아 Date로 처리하는 `parse` 메서드는 `parseByFormat`으로 구현되어, PR머지 되었습니다. https://github.com/day1co/pebbles/pull/25
> `toDate`를 `parse`로 이름 변경

- src/date-util/date-util.spec.ts
- src/date-util/date-util.ts
- date를 특정 format 형식의 string으로 반환하는 함수 추가
- 기존 util/str.js 에도 formatDateToString이란 함수가 있던데 date-util의 format과 통합하고자 합니다.
테스트코드
> feat: date-util에 format 추가

- src/object-util/object-util.spec.ts
- src/object-util/object-util.ts
redstone/util/obj 의 `isEmpty`를 구현합니다.
* lodash의 isEmpty를 참고하였습니다.
테스트 코드
> obj: isEmpty 추가

- src/string-util/string-util.spec.ts
- src/string-util/string-util.ts
nonce 생성함수가 redstone/util에 있음에도 다른 코드들이 util로부터 import하지 않고 각자 함수 생성해서 사용중
redstone/util의 nonce 함수를 getNonce로 바꾸고 toString의 인코딩 인자값을 받을 수 있도록 수정
테스트코드
> feat: string-util에 getNonce 함수 추가(PF-8)

- src/date-util/date-util.interface.ts
- src/http-client/http-client.interface.ts
입력인자의 멤버들은 readonly로 받아야 함수 내부에서 값을 변경하지 못한다
입력인자용 interface는 모든 멤버들을 readonly로 설정
출력인자용 interface는 readonly 해제
> 입력인자 interface 멤버들을 readonly로 변경

- package-lock.json
- package.json
- src/string-util/string-util.interface.ts
- src/string-util/string-util.spec.ts
- src/string-util/string-util.ts
util/str의 renderTemplate
lodash 제거를 위해 util/str의 interpolate를 render의 customTag 사용으로 대체하려 합니다.
(현재 interpolate는 messageService에서 사용중입니다)
mustache dependency 추가
테스트코드
> feat: string util의 renderTemplate 함수 추가

- src/string-util/string-util.ts
https://github.com/day1co/pebbles/pull/54#discussion_r760859294
문자열 -> 배열 치환 부분을 split('') 대신 spread operator를 사용하도록 수정
maskingPart가 배열이 아니어도 되기에 string 타입을 계속 유지하도록 변경
테스트코드
> fix: replace split function with spread operator at string-util

- .github/workflows/ci-test.yml
- .github/workflows/npm-publish.yml
day1co에서 사용하는 npm token의 이름은 NPM_TOKEN이다.
GH_NPM_TOKEN을 NPM_TOKEN으로 변경
> npm token 이름 정정

- .github/workflows/npm-publish.yml
워크플로우 작동 실패 
* `npm version patch` 이후 `package-lock.json` 커밋 추가 
* 커밋 전 `git status` 로 누락된 파일 확인 가능하도록 처리
기존 워크플로우가 npm workspace 기준이어서 커밋시 package-lock.json 을 사용하지 않았고, 현재는 필요하여 추가했습니다.
> FIX: git commit with package-lock.json

- src/object-util/object-util.spec.ts
- src/object-util/object-util.ts
- src/object-util/object-util.type.ts
1. ObjectUtil이므로 deepClone()의 대상을 Object(aka Record<any, any>)로 제한한다.
2. 다만 Buffer 클래스 지원은 차후에 한다.
3. 객체의 값만 비교하는 것은 toEqual()을 쓰면 된다.
4. 테스트하는 객체 종류를 다양하게 만든다.
Type별 객체 생성 코드 수정 및 테스트코드 추가
npm run test
> deepClone 대상을 object로 제한함

- src/date-util/date-util.ts
- src/http-client/http-client.ts
객체를 문자열로 출력하기 위해서는 placeholder를 %o로 쓰면 된다.
JSON.stringify(obj), %s -> obj, %o
> 객체를 로깅할 때는 %o를 쓰도록 수정

- src/boolean-util/boolean-util.ts
regexp 가 `/i` 로 끝나므로 toLowerCase() 를 호출할 필요가 없습니다.
**+ npm - publish 슬랙 메세지 테스트 용도의 pr이기도 합니다.**
BooleanUtil.valueOf에 쓰인 toLowerCase() 함수 제거
테스트코드
> fix: BooleanUtil.valueOf의 불필요한 toLowerCase문을 삭제합니다

- src/date-util/date-util.interface.ts
- src/date-util/date-util.spec.ts
- src/date-util/date-util.ts
- utcOffset 구현 -> 동사형인 offsetUTC로 함수명 변경
- format함수에 분기 추가. default format 인자 추가
- 기존 dateUtil의 utcOffset 결과물은 Moment<>의 instance였는데, 여기서 offset값이 있냐 없냐에 따라 다르게 표현되었습니다. (`Moment<2020-01-01T03:00:00+03:00>` or `Moment<2020-01-01T00:00:00Z>`)
~~이와 유사하게 가기 위해 Date를 상속받은 임의의 class를 만들어 해당 클래스 인스턴스에 offset property를 부여하는 방식으로 접근해봤습니다.~~
- utcOffset은 결과값이 그대로 쓰이지 않고 보통 format함수가 그 값을 감싸는 방식으로 사용되기에 format함수의 수정도 필요했습니다.
- 기존의 format 함수는 런타임 로컬 타임존에 영향을 받기 때문에 그대로 사용할 수 없어서 format 함수도 수정했습니다.
테스트코드
> feat: setUTCOffset(구 utcOffset) 추가 및 format 수정

- src/misc-util/misc-util.spec.ts
- src/object-util/object-util.spec.ts
- src/object-util/object-util.ts
- src/object-util/object-util.type.ts
merge() 구현
deepClone()에서 키가 symbol type인 경우 무시되는 현상 수정
키의 타입에 무관하게 동작하기 위해서 Object.getOwnPropertyNames와 Object.getOwnPropertySymbols 사용
clonedObj[key]가 undefined일 때도 동작하기 위해서 Object.defineProperty를 이용해서 할당
npm run test
> merge() 구현 및 deepClone()에서 symbol type 키가 동작하도록 수정

- src/object-util/object-util.spec.ts
- src/object-util/object-util.ts
ts rewriting 및 lodash 패키지의 omit 기능 지원 중단
lodash의 omit 기능을 참고해 object에서 key를 제거하는 함수를 구현합니다.
기존 함수 스펙은 아래와 같습니다.
1. 기존 object를 변형하지 않도록 합니다.
2. 삭제할 키가 `'a.b.c'` 이처럼 제공된다면, a 오브젝트의, b 오브젝트의, c 키 값을 제거해야 합니다.
테스트코드
> feat: object-util의 omit 구현

- src/date-util/date-util.spec.ts
- src/date-util/date-util.ts
https://fastcampus.atlassian.net/jira/software/projects/PF/boards/72?selectedIssue=PF-25
parseByUnix를 ts로 rewriting합니다.
(moment 의존성 제거로 Moment 객체가 아닌 Date를 반환하도록 수정되었습니다.)
테스트코드
> feat: DateUtil.parseUnixTime 구현 (PF-6)

- src/object-util/object-util.spec.ts
- src/object-util/object-util.ts
1. 존재하지 않는 키가 `omitKeys`의 요소로 들어올 경우 예외처리 안되어 있음
2. `obj` 인자가 빈 객체인 경우 `obj` 인자 형태를 반환하지 않고 {}를 반환함
ex : `omit(new Map(), [1,2]) => return {}` 
3. `obj`나 `omitKeys`가 비었을 경우 기존 `obj`를 그대로 반환 => deepClone된 객체를 반환하는 일반적인 경우와 일관성이 없음
1. for문 돌면서 현재 key에 대한 value가 null | undefined일 경우 throw
2. `obj`나 `omitKeys`가 비었을 경우 `deepClone(obj)`를 반환하도록 수정
3. 테스트코드 추가
테스트코드
> fix: ObjectUtil.omit의 버그 수정

- src/object-util/object-util.spec.ts
- src/object-util/object-util.ts
1. 객체의 모든 key 목록을 반환하는 함수를 구현
2. npm audit fix
getAllPropertyKeys() 구현 및 object key 목록을 만드는 코드 대체
symbol type key들은 Object.keys()(혹은 Object.getOwnPropertyNames())에 반환되지 않아서 getOwnPropertySymbols()를 써야 한다.
따라서 모든 key 목록을 만들려면 Object.getOwnPropertyNames()와 getOwnPropertySymbols()로 만든 list를 합쳐야한다.
npm run test
> getAllPropertyKeys() 구현 & 기존 코드 대체

- src/date-util/date-util.spec.ts
- src/date-util/date-util.ts
- parse 함수에 Date 타입이 들어갔을 시에  인자가 그대로 return 되어 오리지널 값이 변형될 여지가 있습니다.
새로운 Date 객체를 반환하도록 수정 + 테스트코드 추가
테스트코드
> fix: DateUtil.parse 함수가 기존 값을 변형시키지 않도록 합니다

- src/date-util/date-util.spec.ts
- src/date-util/date-util.ts
- format 함수 테스트 도중 `FORMAT_RULE_REGEXP` 정규표현식이 `YYYYMMDDHHmmssSSS` 포맷을 제대로 매치시키지 못하는 에러를 발견하여 수정하였습니다.
- Invalid format인지 테스트하는 부분에서는 
```javascript
if (FORMAT_RULE_REGEXP.test(formatTarget)) {
throw new Error(`Invalid format: ${formatTarget}`);
}
```
기존 스펙에 맞추기 위해 `FORMAT_VERIFICATION_REGEXP` 정규표현식을 별도로 선언하여 사용합니다.
- format의 테스트코드를 추가했습니다.
---
- `formatDate`, `formatDatetime`, `formatTimestamp` 를 추가합니다.
- 기존 redstone/util 스펙과 동일하게, format 함수들의 기본 결과물은 로컬 런타임을 따르도록 하였습니다.
테스트코드
> feat: DateUtil.format 정규표현식 수정 + formatDate, formatDatetime, formatTimestamp 구현

- package-lock.json
- src/date-util/date-util.ts
- src/number-util/number-util.spec.ts
DateUtil.parse()에서 불필요한 new Date()를 하고 있다.
DateUtil.parse()에서 불필요하게 new Date()를 하는 부분 제거
ONE_SECOND -> ONE_SECOND_IN_MILLI
NumberUtil 테스트의 불필요한 toString()제거
npm run test
> DateUtil.parse()의 불필요한 로직 제거

- src/date-util/date-util.interface.ts
- src/date-util/date-util.spec.ts
- src/date-util/date-util.ts
redstone의 `formatLocalDate`, `formatLocalDateShortcut` 함수의 ts 이관입니다.
`formatLocalDate`, `formatLocalDateShortcut` 함수를 하나로 합쳤습니다.
년도 표기 유무 차이만 있기 때문에 `opts` 파라미터에 `skipYear` 값으로 분기점을 설정했습니다.
`Intl.DatetimeFormat`을 활용했습니다.
기존 스펙
1. YY/MM/DD (ddd) {HH|자정|정오} 결과값을 반환합니다.
2. 24시 표기를 기준으로 합니다.
3. 12시, 24시의 경우 정오, 자정으로 표기합니다.
4. 00시일 경우 전날 자정을 반환합니다 (1월1일00시 -> 12월31일24시)
`Intl.DatetimeFormat`에 ko-KR 로케일 지정시 YYYY. MM. DD. 형식으로 반환되기 때문에 replace문으로 슬래시로 변환했습니다.
테스트코드
> feat: DateUtil에 YY/MM/DD (ddd) HH 형식으로 로컬타임을 포맷하는 함수를 추가합니다

- src/date-util/date-util.interface.ts
- src/date-util/date-util.spec.ts
- src/date-util/date-util.ts
`formatLocalDatehourVariant1` 함수 rewriting (https://fastcampus.atlassian.net/browse/DCM-43)
- 함수 스펙
```javascript
formatLocalDatehourVariant1(new Date('2000-01-01 00:00') // => 12월 31일 금요일 자정
formatLocalDatehourVariant1(new Date('2000-01-01 12:00') // => 1월 1일 토요일 정오
formatLocalDatehourVariant1(new Date('2000-01-01 13:00') // => 1월 1일 토요일 13시
```
redstone/util의 `formatLocalDatehourVariant1` 함수 스펙에 맞는 `formatInLongLocalTime` 함수 작성
(더 좋은 함수명이 있을까요? 😅)
포맷 옵션 제공시 `formatInTwoDigitLocalTime` 함수 구현때 작성했던 [`LocalDateTimeFormatOpts`](https://github.com/day1co/pebbles/blob/main/src/date-util/date-util.interface.ts#L23) 를 재활용했습니다
(redstone/util에는 없었던 년도 표기도 가능한 스펙이 추가)
사소하지만 `subtractDayIfLocaTimeIsMidnight` 함수명을 `subtractOneDayIfLocalTimeIsMidnight` 로 변경하였습니다
npm test
> feat: 날짜를 로컬 타임존의 long 형식으로 포맷하는 함수 구현 (DCM-43)

- .eslintrc.js
- tsconfig.json
TS 컴파일 타겟을 node 16이 지원 가능한 es2021로 변경해야한다.
> TS target을 es2021로 수정

- .github/workflows/ci-test.yml
- src/date-util/date-util.ts
calcDatetime 코드가 필요 이상으로 길다.
millisecond 계산이 불가능한 연/월 계산을 제외하고 나머지는 if문 없이 millisecond 계산으로 처리한다.
npm run test
> calcDatetime 코드를 더 짧고 더 효율적으로

- src/date-util/date-util.spec.ts
- src/date-util/date-util.ts
기존 fastcampus/util의 utcOffset 함수는 moment 객체의 offset을 바꾸기 위한 것.
그런데 지금 setUTCOffset 함수는 시각 자체를 바꾸고 있다.
setUTCOffset 함수 삭제
npm run test
> 불필요한 setUTCOffset 함수 제거

- src/http-client/http-client.spec.ts
- src/http-client/http-client.ts
- src/http-client/http-client.type.ts
- src/http-client/index.ts
- src/index.ts
HttpClient 생성시 baseUrl을 입력 인자로 받을 수 있게 함
HttpRes를 deprecated 처리하고 HttpResponse로 대체
npm run test
> HttpClient에 생성자 추가 및 HttpRes를 HttpResponse로 변경

- src/date-util/date-util.spec.ts
- src/date-util/date-util.ts
redstone-database-schema 에서 moment() 의존성을 pebbles로 대체하기 위해 관련 메서드 추가
`beginOfDay` , `endOfDay` 메서드 추가
https://github.com/day1co/redstone-database-schema/pull/21
스펙추가
> DateUtil - beginOfDay, endOfDay 추가

- package-lock.json
- src/date-util/date-util.interface.ts
- src/date-util/date-util.spec.ts
- src/date-util/date-util.ts
- src/date-util/date-util.type.ts
- src/date-util/index.ts
js Date는 'YYYY-MM-DD'를 UTC 0시로 해석한다. 하지만 ISO 표준은 로컬타임 0시다.
parse의 입력으로 'YYYY-MM-DD'가 들어오면 T00:00:00 을 붙여서 Date로 변환
startOf(), endOf() 추가
npm run test
> parse를 표준에 맞게 수정 및 startOf, endOf 추가

- src/date-util/date-util.spec.ts
- src/date-util/date-util.ts
parse 관련 함수들을 모아놓자.
parseByFormat 구현이 필요 이상으로 복잡하다
parseUnixTime은 굳이 string 입력을 받지 말자
parseByFormat, parseTimestamp, parseUnixTime 위치 이동
parseByFormat에서 불필요한 callback 제거
parseUnixTime 입력 타입에서 string 제거
npm run test
> parseByFormat 코드 간략화

- src/string-util/string-util.spec.ts
- src/string-util/string-util.ts
허용 가능한 한국 전화번호 형태가 아니면 기본적으로 throw error를 하되
fallback이 존재하면 fallback을 반환 하도록 수정
npm run test
> normalizeKoreaPhoneNumber에서 fallback이 있으면 throw를 하지 않도록 하자

- src/date-util/date-util.spec.ts
- src/date-util/date-util.ts
parseByFormat에서 잘못된 값이 들어왔을 때에 대한 처리가 없다
월 > 12, 일 > 31, 시각 >= 24, 분  >= 60, 초 >= 60인 값이 있으면 throw Error()
npm run test
> parseByFormat에서 잘못된 시간값이 들어온 경우 throw error

- src/string-util/string-util.interface.ts
- src/string-util/string-util.spec.ts
- src/string-util/string-util.ts
- src/string-util/string-util.type.ts
개인정보 마스킹 로직 적용이 필요하다
개인정보 타입별 마스킹해주는 함수 구현
https://fastcampus.atlassian.net/wiki/spaces/SRE/pages/1983643664/csv
이름: 앞뒤 1자리 외 마스킹 (이모지를 포함하거나 한국 이름이 아닐 수 있음)
전화번호: 중간자리 마스킹 (normalize 되지 않은 전화번호가 포함되어 있을 수 있음 `ex) 010-1234-1234`)
계좌번호: 앞뒤 3자리 외 마스킹
주소: 지번주소라면 동면읍 / 도로명주소라면 도로명 미만 마스킹
- 서울시 강남구 강남대로 111길 11로 11 -> 서울시 강남구 강남대로 xxx~
- 전북 완주군 봉동읍 둔산1로 11 -> 전북 완주군 봉동읍 둔산1로 xx
- 전북 완주군 봉동읍 둔산리 11 -> 전북 완주군 봉동읍 xxx ~
- 지번주소 중 동면읍 단위에서 '가'로 끝나는 주소도 존재 `(ex: 서울 성동구 성수동1~2가, 금호동1~3가 등)`
이메일: 앞에서 3번째 ~ '@' 전까지 마스킹
npm test
> feat: Add maskPrivacy function

- src/object-util/object-util.spec.ts
- src/object-util/object-util.ts
deepClone 대상의 constructor가 undefined인 경우가 있다.
현재의 deepClone에서는 대상의 constructor를 이용해 결과물을 생성하기 때문에 이런 경우 오류가 발생한다.
constructor가 undefined면 new Object()로 deepClone 결과물을 생성한다.
npm run test
> deepClone시 constructor가 undefined면 new Object()로 생성

- src/object-util/object-util.spec.ts
- src/object-util/object-util.ts
omit 대상 객체의 특정 키에 대한 값이 nullish한 경우 해당 key가 삭제되지 않는다
값의 nullish 여부를 떠나 키가 존재하면 삭제하도록 수정
테스트 케이스 추가
npm run test
> nullish한 값을 가진 key가 존재할 때 key가 삭제되지 않는 버그

- src/string-util/string-util.spec.ts
- src/string-util/string-util.ts
splitTags의 str 기본값을 빈 스트링으로 설정하여 입력값이 undefined일 경우 발생하는 예외를 보완
스모크 테스트
> fix: set default value of str to empty string in splitTags

- src/string-util/string-util.spec.ts
- src/string-util/string-util.ts
This reverts commit d160402021726ca231107439d49597d2448c0a11.
#136 을 리버트 합니다.
휴먼 아이
> Revert "fix: set default value of str to empty string in splitTags"

- src/object-util/object-util.spec.ts
- src/object-util/object-util.ts
isEmpty의 object 체크를 typeof로 변경합니다
`const obj = Object.create(null);` 일 경우 instanceof object로 체크가 되지 않아 잘못된 결과가 반환됩니다
스모크 테스트
> fix: isEmpty의 object 체크를 typeof로 변경

- src/object-util/object-util.spec.ts
isEmpty 테스트 항목이 true return과 false return으로 구분되어있는데 새로 추가된 테스트가 이를 어겼다
true return 항목에 들어있는 false return 테스트를 false return 항목으로 옮김
npm run test
> true return과 false return 구분에 맞게 isEmpty 테스트 순서 조정

- src/exception/client-exception/changed-credential-exception.ts
- src/exception/client-exception/index.ts
- src/exception/exception.spec.ts
- src/exception/index.ts
- src/index.ts
[auth token dao] (https://github.com/day1co/redstone/blob/c29d3c678c9343f6f073b0e1ed115e068306f40e/auth/src/dao/token.js#L1)
에서  CredentialChangedException로 require 하고 있습니다.
ChangedCredentialException 보다 CredentialChangedException 네이밍이 정확 할 것 같아 수정하고자 합니다.
> fix: ChangedCredentialException를 CredentialChangedException로 변경

- src/http-client/http-client.spec.ts
- src/http-client/http-client.ts
Http Patch request에 해당하는 메소드가 없다
sendPatchRequest() 추가
npm run test
> HttpClient에 patch request 메소드를 추가

- src/logger/logger-impl/pino-logger.ts
- src/logger/logger.interface.ts
NestJS에 external logger로 pebbles/logger를 적용하려 하다보니 Logger에 log() 함수가 없어서 컴파일 에러가 발생한다.
(NestJS이ㅡ LoggerService interface 참고)
Logger interface에 log() 함수 추가. log()는 debug()와 동일
사실 NestJS에서 app.userLogger(logger); 를 컴파일 통과시키기 위해 만든 기능이고
log() 함수의 스펙은 전혀 정해진 바가 없다
휴먼 아이
> Logger interface에 log 메소드 추가

- src/string-util/string-util.spec.ts
- src/string-util/string-util.ts
https://fastcampus.atlassian.net/browse/COL-2130
https://fastcampus.atlassian.net/browse/COL-2138
변경된 정책 : https://fastcampus.atlassian.net/wiki/spaces/SRE/pages/2127757380/2022.05.+csv
전화번호는 앞 3글자, 뒤 4글자 제외 모두 마스킹처리
이름은 emoji, 히라가나 관련 정규식을 통해 2글자는 맨뒤, 3글자 이상은 맨 앞 맨 뒤 제외 마스킹
😆같은 이모지는 각각 1~3개의 공간을 차지하며 배열로 ["","😆",""]로 인식하며,
‍👩‍👧같은 다중 이모지는 ["👩","","👩","","👧"]로 인식해서 이름의 길이가 늘어나게 되며, 히라가나 관련 정규식이 잘못되어 있었습니다.
해서 이름 관련 마스킹을 따로 빼서 이모지등 모든 글자는 1글자로 인식하게 한 뒤, 맨 앞 맨 뒤 글자 제외하고 모두 *처리 했습니다.
string-util.spec.ts에서 테스트 진행
> change masking policy about phone and fix bug about emoji and jp

- src/number-util/number-util.spec.ts
- src/number-util/number-util.ts
isNumeric이 '', '  ' 같은 공백 문자열을 걸러주지 못함.
js에서 사용할 때는 null도 걸러주지 못함.
공백문자열일때 false 반환하도록 변경
> Number-util: isNumeric 공백 처리

- src/number-util/number-util.spec.ts
- src/number-util/number-util.ts
원칙적으론 string 타입여부를 검사하는 것은 호출하는 쪽의 몫이지만...
#155 결과... 문자열이 아닌 값이 들어오면 runtime error를 발생
```
TypeError: numStr.trim is not a function ...
```
`Number()`와 `parseFloat()`의 edge case(`null`, `undefined`, `''` 빈문자열...) 처리가 다르다는 점을 활용.
둘의 결과가 같고 그 결과가 숫자라면 일반적인(?) 숫자라고 판단.
> fix isNumberic runtime error on edge case

- src/unit-util/unit-converters/byte-unit-converter.spec.ts
- src/unit-util/unit-converters/byte-unit-converter.ts
- src/unit-util/unit-converters/money-unit-converter.spec.ts
- src/unit-util/unit-converters/money-unit-converter.ts
- src/unit-util/unit-util.interface.ts
unit-converter interface에서 size 제거하고 value를 필수 속성으로 변경
MoneyUnitConverter에서 음수 지원 및 관련 테스트 추가
money의 경우 환불시 음수이기 때문에 음수를 지원해야 함
npm run test
> unit-converter에서 size를 없애고 value를 필수 속성으로 변경

- .github/workflows/ci-test.yml
- .github/workflows/npm-publish.yml
- .github/workflows/pr-labeler.yml
- .github/workflows/release-drafter.yml
https://fastcampus.atlassian.net/browse/COMMON-157
깃헙에서 사용하는 npm 관련 토큰을 GH_TOKEN 으로 통일
> change GitHub npm package manage token of secrets to GH_TOKEN

- src/map-util/map-util.spec.ts
- src/map-util/map-util.ts
array of object `[{id: 1, ...}, ...]` 에서, 오브젝트의 키를 명시하면 Map<T[K], [T]> 를 리턴하는 함수를 추가합니다.
> feat: Add MapUtil.groupByKey

- src/type-util/index.ts
- src/type-util/type-util.spec.ts
- src/type-util/type-util.type.ts
- 인터페이스의 특정 속성만 Pick 또는 Omit 하고 나머지 속성은 Partial 할 수 있다면, 더 자유롭게 타입/인터페이스를 사용가능할 것 같습니다.
- 이런 타입이 정말 유용할지... 아주 특별한 상황(edge case)에서만 쓰이는건가 싶어서... 일단 PR 만들어보았습니다.
- 네이밍이 한참 부족합니다. 필요한지 여부를 판단해주시고, 그 다음으로 네이밍에 대해 의견주시면 감사하겠습니다 🙇‍♂️
- 전체 속성중 일부 속성만 Pick, 나머진 Partial이 적용된 PickWithPartial 을 추가합니다.
- 전체 속성중 Optional 속성의 타입을 Required로 받도록 하는 RequiredPartialProps 을 추가합니다.
타입이다보니 테스트 코드를 어떻게 작성해야하나 싶어 일단 해당 타입을 어떻게 사용할 수 있는지 보여주기 위한 목적으로 타입 단언을 사용한 테스트 코드를 추가하였습니다.
> feat: PickWithPartial, RequiredPartialProps 추가

- src/type-util/index.ts
https://github.com/microsoft/TypeScript/issues/37238
export type을 해줄 때는 *를 사용할 수 없다.
> fix: Only named exports may use 'export type'

- package.json
- src/date-util/date-util.interface.ts
- src/date-util/date-util.spec.ts
- src/date-util/date-util.ts
moment.fromNow()를 직접 사용하는 곳을 대체하기 위한 기능 필요
https://github.com/search?q=org%3Aday1co%20OR%20org%3Afastcampus%20OR%20org%3Aday1coloso%20OR%20org%3Aday1snowball%20OR%20org%3Aday1lemonade%20fromNow&type=code
DateUtil.fromNow() 추가.
인자로 받은 날짜와 현재가 얼마나 차이 나는지 적당한 년/월/일 시/분/초 차이로 표기해주는 기능입니다.
현재 시간이 2020-01-01 00:00:00 이라 했을때,
2019-02-15 00:00:00 와의 차이는 정확하게는 11개월이 안됩니다만, 기존 moment.fromNow() 는 11달이라 표기하고 있어 이에 맞추기 위해 diff에 ignoreAccuracy 옵션을 추가했습니다.
npm test
> feat: Add fromNow()

- src/misc-util/misc-util.spec.ts
- src/misc-util/misc-util.ts
- setNextPagination을 통해 next disabled 체크가 가능하도록 limit를 하나 늘려준다.
- maxLimit를 둬서 필요 이상의 데이터를 요청하지 못하도록 제한한다.
<Previous | Next> 페이징을 사용하기 위한 기능입니다.
> feat: setNextPagination 기능 보완

- src/number-util/number-util.spec.ts
- src/time-range/time-range.spec.ts
- src/time-range/time-range.ts
[feature/time-ragne-decimal](https://github.com/day1co/pebbles/pull/197) 에서 이어지는 PR입니다.
merge(), totalinterval() 작업시에도 부동소수점을 방어하는 계산을 적용합니다.
두 함수 모두 서비스에서 사용하고있는걸 고려하여 적용했지만 검토가 필요합니다.
jest 테스트 추가
> fix: time-range의 interval 계산시 부동소수점 방어

- src/number-util/number-util.ts
- src/time-range/time-range.spec.ts
- src/time-range/time-range.ts
~skillflo에서 time-range 운영시 100% 시청했음에도,~
~100%로 계산되지 않는 문제가 생겨 오차범위를 보정하는 계산을 추가합니다.~
~TimeRange 클래스는 단일 클립의 재생시간을 다루지만~
~보정값을 더한 시간 계산에는 비즈니스가 공통으로 사용될것으로 보여 기존 클래스에 추가하였습니다.~
- 소수점자리수 미사용시(0) 계산 로직을 넘어감
- 기본 소수점처리는 반올림 처리 되도록 개선
- ~increaseCorrection(:number) 추가~
수강률 정책 정리 https://fastcampus.atlassian.net/wiki/spaces/BPOLMS/pages/2615181602/-+23.12.18
테스트 추가
> time-range: 반올림처리 개선

- src/crypto-util/crypto-util.spec.ts
- src/crypto-util/crypto-util.ts
AESKey 를 안전하게 만들기 위해 createAesKey 메서드를 추가 합니다. 
MDN 에 따르면 암호화 키를 만들때는 getRandomValues() 대신 generateKey() 를 사용하라고 합니다. 
https://developer.mozilla.org/en-US/docs/Web/API/Crypto/getRandomValues
```
Don't use getRandomValues() to generate encryption keys. Instead, use the [generateKey()](https://developer.mozilla.org/en-US/docs/Web/API/SubtleCrypto/generateKey) method. There are a few reasons for this; for example, getRandomValues() is not guaranteed to be running in a secure context.
```
> feat: CryptoUtil.createAesKey 추가 

- src/time-range/time-range.spec.ts
- src/time-range/time-range.ts
merge 할때 interval 계산시 소수점을 반영.
```
// 카테노이드의 데이터를 최대한 원본을 유지할때
const timeRange2 = new TimeRange([], 5);
```
테스트코드 추가
> time-range: merge 함수에서 interval계산에 소수점을 반영

- src/time-range/time-range.spec.ts
- src/time-range/time-range.ts
미시청구간을 구해야 한다.
시청구간과 마지막클립 시간을 이용해 미시청 구간을 구합니다.
test code
> feat: 시청구간을 이용하여 미시청구간을 구하는 기능 추가

- src/map-util/map-util.ts
MapUtil.get 은 defaultValue 를 받을 수 있습니다. 
이것을 Map.get() 이 undefined 유니언 타입을 리턴하는 것에 대한 방어 차원으로 사용할 수 있습니다.
그런데 용도에 맞지 않게 undefined 유니언 타입이 리턴되고 있어 함수 오버로딩을 통해 지원하도록 수정했습니다.
> fix: MapUtil.get return type, to use function overloading

- src/time-range/time-range.spec.ts
- src/time-range/time-range.ts
콜러스는 클립에 지정된 마감시간보다 더 적게 측정되는 경우가 있다.
이런 경우 강의클립을 다 시청하였더라도 미시청구간이 발생된다.
마지막 구간의 경우 반올림 처리하여 미시청구간을 없애도록 한다.
test code
> refactor: 미시청 마지막 구간에서 decimal 옵션으로 처리하도록 수정

- src/date-util/date-util.const.ts
- src/date-util/date-util.spec.ts
- src/date-util/date-util.ts
https://fastcampus.atlassian.net/browse/COL-5261
- [IANA DataBase](https://en.wikipedia.org/wiki/List_of_tz_database_time_zones) 공식 지원 속성인 PST8PDT로 변경.
PST는 태평양 표준시(Pacific Standard Time)를 의미합니다. 그러나 “PST”는 Intl.DateTimeFormat에서 사용할 수 있는 유효한 IANA 시간대 식별자가 아닙니다.
x
스모크
> fix: change timezone pst value to pst8pdt

- src/logger/logger-impl/pino-logger.ts
- src/logger/logger.interface.ts
- src/logger/logger.spec.ts
log 가독성을 높이기 위해 pino.child 추가
[https://github.com/pinojs/pino](https://github.com/pinojs/pino)
없음
스모크, 스웨거
> feat : pino child 추가

- src/time-range/time-range.spec.ts
- src/time-range/time-range.ts
timeRange가 이동 없이 시청하여도 네트워크 및 환경 이슈로 시청구간이 끊기는 경우가 발생됩니다.
https://fastcampus.atlassian.net/browse/FCLXP-6928
구간시간의 앞뒤로 buffer 시간을 설정하여 관련 이슈를 해소하고자 합니다.
로컬 및 staging 테스트
> Feat: timeRange에 앞뒤로 buffer sec 추가

- src/time-range/time-range.spec.ts
- src/time-range/time-range.ts
timeRange 생성과 add 를 동시에 사용하는 곳이 있어서 버퍼 시간이 중복으로 생성된다.
bufferAdd 와 add를 분리하여 사용하기로함
> fix: add buffer add function

- src/date-util/date-util.spec.ts
- src/date-util/date-util.ts
실행 context와 무관하게 특정 시간대의 시작일과 종료일을 리턴하는 메소드가 필요해서 추가합니다.
정산에서 특정 월에 해당하는 시작일과 종료일이 필요한 경우가 있습니다.
ex)
**2024년1월**
* kst: 2024-01-01T00:00:00Z ~ 2024-02-01T00:00:00Z
* ust: 2023-12-31T15:00:00Z ~ 2024-01-31T15:00:00Z
자세한 내용은 테스트 코드에 추가해두었습니다.
테스트 코드
> feat: Add startOfByTimezone and endOfByTimezone functions

- src/string-util/string-util.spec.ts
- src/string-util/string-util.ts
- src/string-util/string-util.type.ts
고객 생일 성별 컬럼 마스킹을 위한 타입추가
두 컬럼명과 같게 가려고 했으나 이와같이 모든 문자를 마스킹하는 케이스가 더 나올수가 있을거같아서 default로 추가하였습니다. 의견들어보고 따로 추가할지 그대로 가야할지 정하겠습니다.
> add mask type default for masking all text

- src/exception/client-exception/too-many-requests-exception.ts
- 429 error 사용
- 429 client error 추ㅏ
x
휴먼 아이
> feat: add too many requests error

- src/time-range/time-range.spec.ts
- src/time-range/time-range.ts
로직 변경 및 사유
로직 변경 사유
- interval은 반올림을 한번만 실행되고, total은 반올림이 두번 실행된다.
- total은 interval보다 클 수 없지만, 반올림으로 인해, total이 큰 경우가 생긴다.
로직 변경
- interval을 계산 시, 반올림이 된 start, end의 값을 비교하여 더 큰 수를 interval에 더한다
totalPlayTime은 start, end의 반올림을 실행하고
totalInterval은 interval의 반올림만 실행한다.
예시)
```
const first = [{"end": 28.37231, "start": 0, "interval": 28.37231}];
const second = [
{"end": 13.87707, "start": 0, "interval": 13.87707},
{"end": 99.76297, "start": 85.45316, "interval": 14.30981},
{"end": 360.66692, "start": 314.84983, "interval": 45.81709}
];
const third = [{"end": 95.42274, "start": 0, "interval": 95.42274}];
```
의 데이터에서
interval만 반올림하여 더하면
28 + 14+ 14+ 46 + 95로 197이 나오지만
start, end를 반올림하여 end-start를 계속 더하면
(28 - 0) + (14 - 0) + (100 - 85) + (361 - 315) + (95 - 0)으로 198이 나오게 된다.
interval이 …
> feat/modify member_clip_progress interval logic

- src/boolean-util/boolean-util.spec.ts
- src/boolean-util/boolean-util.ts
- src/boolean-util/index.ts
- src/date-util/date-util.spec.ts
- src/date-util/date-util.ts
- src/date-util/index.ts
- src/map-util/index.ts
- src/map-util/map-util.spec.ts
- src/map-util/map-util.ts
- src/number-util/index.ts
- src/number-util/number-util.spec.ts
- src/number-util/number-util.ts
- src/object-util/object-util.ts
- src/string-util/string-util.ts
- src/unit-util/unit-converters/byte-unit-converter.ts
#243 에 머지하는 PR입니다
오래되었거나, 대체하는 기능이 생겼거나, 중복되거나, 쓰이지 않는 method들을 대량 정리합니다
- boolean-util / `valueOf` -> `parseBoolean`
안 쓰이는 줄 알았는데 환경변수 해석할 때 꽤 많이 쓰이고 있었습니다… 더 나은 이름으로 갱신합니다
- map-util / `get` -> **삭제**
Map#get과 중복됩니다.
- number-util / `valueOfNumber` -> **삭제**
사용 0건. 대부분 위에 있는 (int)valueOf를 사용하고 있습니다.
- object-util / `serialize`, `deserialize` -> **deprecated**
겸사겸사 잘못 지정되어 있는 타입을 수정합니다. (JSON.parse는 직렬화될 수 있는 아무 타입이나 리턴할 수 있습니다)
- object-util / `isNullish` -> **deprecated**
`== null`을 권장합니다.
- object-util / `deepClone` -> **deprecated**
[`structuredClone`](https://developer.mozilla.org/ko/docs/Web/API/Window/structuredClone)을 권장합니다.
- string-util / `splitString`, `joinStrings` -> **deprecated**
…
> 4.x deprecations (and more)

- src/time-range/time-range.ts
timeRange의 interval이 undefined이면 0으로 값을 전달하게 하여, decimaldown에서 에러를 반환하지 않게 방어코드 추가
> add/interval undefined 시, 방어 코드 추가
